<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>disable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.7" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.7" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.7">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.18.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\..\Shared\Be.Haven.ApiCommon\Be.Haven.ApiCommon.csproj" />
      <ProjectReference Include="..\Authentication.Infrastructure\Authentication.Infrastructure.csproj" />
    </ItemGroup>

</Project>
