// Global using directives
global using System.Text.Json.Serialization;
global using System.Text.Json.Nodes;
global using Asp.Versioning;
global using Authentication.Api.Extensions;
global using Authentication.Api.Constants;
global using Authentication.Api.Filters;
global using Authentication.Api.Swagger.Examples;
global using Authentication.Domain.Enums;
global using Authentication.Application.Extensions;
global using Authentication.Infrastructure.Extensions;
global using Authentication.Infrastructure.Options.Authentications;
global using Authentication.Infrastructure.Options.ExternalProviders;
global using Be.Haven.ApiCommon.Extensions;
global using Be.Haven.ApiCommon.Middlewares;
global using Be.Haven.ApiCommon.Routing;
global using Be.Haven.Cache.Extensions;
global using Be.Haven.Core.Extensions.Configurations;
global using Be.Haven.Core.Extensions.DI;
global using Be.Haven.Core.Exceptions;
global using Be.Haven.Shared.Dtos.Options.Gcp;
global using Mediator;
global using Microsoft.AspNetCore.Authorization;
global using Microsoft.AspNetCore.Http;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.AspNetCore.Mvc.Filters;
global using Microsoft.AspNetCore.Mvc.ApplicationModels;
global using Microsoft.AspNetCore.Server.Kestrel.Core;
global using Microsoft.Extensions.Hosting;
global using Microsoft.OpenApi;
global using Swashbuckle.AspNetCore.SwaggerGen;
global using static Authentication.Api.Constants.ControllerRouteConstants;
global using static Authentication.Api.Constants.ApiConstants;
global using static Be.Haven.Shared.Constants.AppConstants.SystemVariable;
global using static Be.Haven.Shared.Constants.AuthConstants;
global using static Be.Haven.Shared.Constants.ApiConstants;
global using Authentication.Application.Commands.ChangeForgotPassword;
global using Authentication.Application.Commands.VerifyForgotPasswordOtp;
global using Authentication.Application.Commands.VerifyRegisterEmail;
global using Authentication.Application.Commands.ForgotPassword;
global using Authentication.Application.Commands.Login;
global using Authentication.Application.Commands.ChangePassword;
global using Authentication.Application.Commands.ChangeEmail;
global using Authentication.Application.Commands.DeleteUserVehicle;
global using Authentication.Application.Commands.ExternalUnlink;
global using Authentication.Application.Commands.ExternalLink;
global using Authentication.Application.Commands.Kyc;
global using Authentication.Application.Commands.Logout;
global using Authentication.Application.Commands.RefreshToken;
global using Authentication.Application.Commands.Register;
global using Authentication.Application.Commands.RegisterUserVehicle;
global using Authentication.Application.Commands.SwitchParty;
global using Authentication.Application.Commands.UpdateUserInfo;
global using Authentication.Application.Commands.VerifyChangeEmailOtp;
global using Authentication.Application.Commands.ExternalLogin;
global using Authentication.Application.Dtos.Users.Contexts;
global using Authentication.Application.Dtos.Users.ExternalProviders;
global using Authentication.Application.Dtos.Users.Kyc;
global using Authentication.Application.Dtos.Users.Profiles;
global using Authentication.Application.Dtos.Users.Sessions;
global using Authentication.Application.Dtos.Users.Vehicles;
global using Authentication.Application.Queries.UserInfo;
global using Authentication.Application.Queries.UserVehicles;
global using Be.Haven.ApiCommon.Swagger;
global using Be.Haven.ApiCommon.Swagger.Attributes;
global using Be.Haven.Shared.Dtos;
global using static Authentication.Application.Constants.ApplicationErrorConstants;
global using Be.Haven.ApiCommon.Factories;
global using Be.Haven.ApiCommon.Filters;
