// Global using directives
global using System.Collections.Concurrent;
global using System.Globalization;
global using System.Security.Cryptography;
global using System.Text;
global using System.Text.RegularExpressions;
global using Be.Haven.Cache.Extensions;
global using Be.Haven.Cache.Helpers;
global using Be.Haven.Cache.Interfaces;
global using Be.Haven.Cache.Models;
global using Be.Haven.Cache.Services;
global using Be.Haven.Core.Exceptions;
global using Be.Haven.Core.Extensions.Objects;
global using Be.Haven.Core.Interfaces.Caches;
global using Be.Haven.Core.Interfaces.Concurrency;
global using Be.Haven.Core.Interfaces.Services;
global using Be.Haven.Core.Services;
global using Be.Haven.Shared.Constants;
global using Be.Haven.Shared.Constants.Errors;
global using Be.Haven.Shared.Constants.System;
global using Be.Haven.Shared.Dtos.Options.Caching;
global using Be.Haven.Shared.Dtos.Options.Gcp;
global using Mediator;
global using Microsoft.Extensions.Caching.Distributed;
global using Microsoft.Extensions.Caching.StackExchangeRedis;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Logging;
global using Microsoft.Extensions.Options;
global using Medallion.Threading.Redis;
global using StackExchange.Redis;
global using static Be.Haven.Shared.Constants.System.AppConstants.SystemVariable;
global using static Be.Haven.Shared.Constants.Authentication.AuthConstants;
global using static Be.Haven.Shared.Constants.Logging.CoreLogConstants;
global using static Be.Haven.Shared.Constants.Errors.ErrorConstants.RedisErrors;
global using static Be.Haven.Shared.Constants.Cache.RedisConstants;
global using static Be.Haven.Shared.Constants.Cache.RedisConstants.EnvironmentVariables;
global using static Be.Haven.Shared.Constants.Cache.RedisConstants.ErrorMessage;
