// Global using directives

global using Be.Haven.Cache.Interfaces;
global using Be.Haven.Cache.Models;
global using Be.Haven.Cache.Services;
global using Be.Haven.Cache.Helpers;
global using Be.Haven.Core.Extensions.Objects;
global using Be.Haven.Core.Interfaces.Services;
global using Be.Haven.Core.Interfaces.Services.Gcp;
global using Be.Haven.Shared.Dtos.Options.Caching;
global using Be.Haven.Shared.Dtos.Options.Gcp;
global using Mediator;
global using Microsoft.Extensions.Caching.Distributed;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Logging;
global using Microsoft.Extensions.Options;
global using StackExchange.Redis;
global using System.Collections.Concurrent;
global using System.Security.Cryptography;
global using System.Text;
global using static Be.Haven.Shared.Constants.AppConstants.SystemVariable;
global using static Be.Haven.Shared.Constants.RedisConstants;
global using static Be.Haven.Shared.Constants.CoreLogConstants;
global using static Be.Haven.Shared.Constants.RedisConstants.EnvironmentVariables;
global using static Be.Haven.Shared.Constants.RedisConstants.ErrorMessage;
global using static Be.Haven.Shared.Constants.RedisConstants.MessageInfo;
global using System.Text.RegularExpressions;
global using Be.Haven.Core.Interfaces.Caches;
global using Be.Haven.Core.Interfaces.Quartz;
global using Be.Haven.Core.Services;
global using Google.Cloud.SecretManager.V1;
global using static Be.Haven.Shared.Constants.AuthConstants;
