// Global using directives
global using System.Data;
global using System.Reflection;
global using System.Globalization;
global using Be.Haven.Cache.Behaviours;
global using Be.Haven.Cache.Extensions;
global using Be.Haven.Cache.Interfaces;
global using Be.Haven.Cache.Models;
global using Be.Haven.Core.Behaviors;
global using Be.Haven.Core.Exceptions;
global using Be.Haven.Core.Extensions.DI;
global using Be.Haven.Core.Extensions.Objects;
global using Be.Haven.Core.Extensions.Validations;
global using Be.Haven.Core.Interfaces.Commands;
global using Be.Haven.Core.Interfaces.Queries;
global using Be.Haven.Core.Interfaces.Repositories;
global using Be.Haven.Core.Interfaces.Services;
global using Be.Haven.Shared.Dtos;
global using Be.Haven.Shared.Dtos.Responses;
global using FluentValidation;
global using Haven.Application.Commands.CreateProperty;
global using Haven.Application.Constants;
global using Haven.Application.Dtos.Properties.Common;
global using Haven.Application.Dtos.Properties.Create;
global using Haven.Application.Dtos.Properties.Detail;
global using Haven.Application.Dtos.Properties.List;
global using Haven.Application.Extensions;
global using Haven.Application.Helpers;
global using Haven.Application.Interfaces.Repositories;
global using Haven.Application.Interfaces.Services;
global using Haven.Application.Models.Locations;
global using Haven.Application.Models.MasterData;
global using Haven.Application.Models.Parties;
global using Haven.Application.Models.Properties.Create;
global using Haven.Application.Models.Properties.Detail;
global using Haven.Application.Models.Properties.List;
global using Haven.Application.Models.Properties.QueryParameters;
global using Haven.Application.Models.Properties.Rows;
global using Haven.Application.Queries.GetProperties;
global using Haven.Application.Queries.GetPropertyDetail;
global using Haven.Domain.Entities;
global using Haven.Domain.Enums;
global using Mapster;
global using Microsoft.AspNetCore.Http;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Logging;
global using static Be.Haven.Shared.Constants.AppConstants.SystemMessageCode;
global using static Be.Haven.Shared.Constants.AppConstants.SystemVariable;
global using static Haven.Application.Constants.ApplicationConstants;

