<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>disable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Haven.Core\Haven.Core.csproj" />
      <ProjectReference Include="..\Haven.Shared\Haven.Shared.csproj" />
    </ItemGroup>

</Project>
