// Global using directives
global using Asp.Versioning;
global using Be.Haven.Core.Exceptions;
global using Be.Haven.Core.Extensions.Configurations;
global using Be.Haven.Core.Extensions.Objects;
global using Be.Haven.Core.Extensions.Serializations;
global using Be.Haven.Core.Factories;
global using Be.Haven.Core.Helpers;
global using Be.Haven.Core.Interfaces.Events;
global using Be.Haven.Core.Interfaces.Factories;
global using Be.Haven.Core.Interfaces.Repositories;
global using Be.Haven.Core.Interfaces.Services;
global using Be.Haven.Core.Interfaces.Services.Gcp;
global using Be.Haven.Core.Jobs;
global using Be.Haven.Core.Models;
global using Be.Haven.Core.Models.ClientDevices;
global using Be.Haven.Core.Models.FileResponse;
global using Be.Haven.Core.Models.ObjectStorage;
global using Be.Haven.Core.Repositories;
global using Be.Haven.Core.Services;
global using Be.Haven.Core.Services.Gcp;
global using Be.Haven.Core.Services.R2;
global using Be.Haven.Shared.Configurations;
global using Be.Haven.Shared.Constants;
global using Be.Haven.Shared.Dtos;
global using Be.Haven.Shared.Dtos.Attributes;
global using Be.Haven.Shared.Dtos.Options.Data;
global using Be.Haven.Shared.Dtos.Options.Email;
global using Be.Haven.Shared.Dtos.Options.Authentications;
global using Be.Haven.Shared.Dtos.Options.Caching;
global using Be.Haven.Shared.Dtos.Options.Gcp;
global using Be.Haven.Shared.Dtos.Options.Observability;
global using Be.Haven.Shared.Dtos.Options.Scheduling;
global using Be.Haven.Shared.Dtos.Options.Storage;
global using Be.Haven.Shared.Dtos.Requests;
global using Be.Haven.Shared.Dtos.Requests.Emails;
global using Be.Haven.Shared.Dtos.Responses;
global using Be.Haven.Shared.Enums;
global using ClosedXML.Excel;
global using Dapper;
global using FluentValidation;
global using FluentValidation.Results;
global using Google.Api.Gax;
global using Google.Cloud.PubSub.V1;
global using Google.Cloud.SecretManager.V1;
global using Google.Cloud.Storage.V1;
global using Google.Protobuf;
global using Mapster;
global using Mediator;
global using Microsoft.AspNetCore.Authentication;
global using Microsoft.AspNetCore.Builder;
global using Microsoft.AspNetCore.Diagnostics.HealthChecks;
global using Microsoft.AspNetCore.Http;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.AspNetCore.Mvc.Filters;
global using Microsoft.AspNetCore.Mvc.Infrastructure;
global using Microsoft.AspNetCore.Mvc.ModelBinding;
global using Microsoft.AspNetCore.OData.Query;
global using Microsoft.Data.SqlClient;
global using Microsoft.Data.Sqlite;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.Metadata.Builders;
global using Microsoft.EntityFrameworkCore.Storage;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Diagnostics.HealthChecks;
global using Microsoft.Extensions.Hosting;
global using Microsoft.Extensions.Logging;
global using Microsoft.Extensions.Options;
global using Microsoft.OData;
global using Microsoft.OData.Edm;
global using Microsoft.OData.UriParser;
global using Newtonsoft.Json;
global using Newtonsoft.Json.Linq;
global using Newtonsoft.Json.Serialization;
global using OpenTelemetry;
global using OpenTelemetry.Metrics;
global using OpenTelemetry.Resources;
global using OpenTelemetry.Trace;
global using PdfSharp;
global using PdfSharp.Drawing;
global using PdfSharp.Fonts;
global using PdfSharp.Pdf;
global using Polly;
global using Polly.CircuitBreaker;
global using Polly.Retry;
global using SendGrid;
global using SendGrid.Helpers.Mail;
global using Serilog;
global using Serilog.Context;
global using Serilog.Events;
global using Serilog.Formatting.Compact;
global using System.Collections;
global using System.Collections.Concurrent;
global using System.ComponentModel;
global using System.ComponentModel.DataAnnotations;
global using System.Data.Common;
global using System.Diagnostics;
global using System.Globalization;
global using System.IdentityModel.Tokens.Jwt;
global using System.Linq.Expressions;
global using System.Net;
global using System.Net.Http.Headers;
global using System.Numerics;
global using System.Reflection;
global using System.Runtime.CompilerServices;
global using System.Security.Claims;
global using System.Security.Cryptography;
global using System.Text;
global using System.Text.Json;
global using System.Text.Json.Serialization;
global using System.Text.RegularExpressions;
global using Be.Haven.Core.Formatters;
global using Be.Haven.Core.Handlers;
global using Be.Haven.Core.Interceptors;
global using Be.Haven.Core.Interfaces.Caches;
global using Be.Haven.Core.Interfaces.Excel;
global using Be.Haven.Core.Interfaces.Providers;
global using Be.Haven.Core.Interfaces.Quartz;
global using Be.Haven.Core.Interfaces.Softs.IIsActive;
global using Be.Haven.Core.Providers;
global using Microsoft.EntityFrameworkCore.Diagnostics;
global using Microsoft.Extensions.Caching.Distributed;
global using Microsoft.Extensions.Caching.Memory;
global using Quartz;
global using RedLockNet;
global using RedLockNet.SERedis;
global using RedLockNet.SERedis.Configuration;
global using Serilog.Core;
global using Serilog.Enrichers.OpenTelemetry;
global using Serilog.Extensions.Hosting;
global using Serilog.Formatting;
global using Serilog.Formatting.Display;
global using StackExchange.Redis;
global using static Be.Haven.Shared.Constants.AppConstants.MethodCode;
global using static Be.Haven.Shared.Constants.AppConstants.ODataConstant;
global using static Be.Haven.Shared.Constants.AppConstants.SystemMessage;
global using static Be.Haven.Shared.Constants.AppConstants.SystemMessageCode;
global using static Be.Haven.Shared.Constants.AppConstants.SystemVariable;
global using static Be.Haven.Shared.Constants.ObjectStorageConstants;
global using static Be.Haven.Shared.Constants.R2StorageConstants;
global using static Be.Haven.Shared.Constants.CoreLogConstants;
global using static Be.Haven.Shared.Constants.DataPrivacyConstants;
global using static Be.Haven.Shared.Constants.AuthConstants;
global using static Be.Haven.Shared.Constants.RedisConstants.EnvironmentVariables;
global using static Be.Haven.Shared.Constants.RedisConstants.ErrorMessage;
global using static Be.Haven.Shared.Constants.RedisConstants.MessageInfo;
global using static System.Text.Encoding;
global using Convert = System.Convert;
global using Encoding = System.Text.Encoding;
global using ILogger = Microsoft.Extensions.Logging.ILogger;
global using TopicName = Google.Cloud.PubSub.V1.TopicName;
global using ValidationException = Be.Haven.Core.Exceptions.ValidationException;
global using ValidationResult = System.ComponentModel.DataAnnotations.ValidationResult;
