global using System.ComponentModel.DataAnnotations;
global using System.Globalization;
global using System.IdentityModel.Tokens.Jwt;
global using System.Net;
global using System.Security.Claims;
global using System.Security.Cryptography;
global using System.Text;
global using System.Text.Json;
global using Authentication.Application.Constants;
global using Authentication.Application.Dtos.Authentications.ExternalProviders;
global using Authentication.Application.Dtos.Authentications.Otp;
global using Authentication.Application.Dtos.Authentications.Passwords;
global using Authentication.Application.Dtos.Authentications.Register;
global using Authentication.Application.Dtos.Authentications.Sessions;
global using Authentication.Application.Dtos.Users.Contexts;
global using Authentication.Application.Dtos.Users.ExternalProviders;
global using Authentication.Application.Dtos.Users.Kyc;
global using Authentication.Application.Dtos.Users.Profiles;
global using Authentication.Application.Dtos.Users.Sessions;
global using Authentication.Application.Interfaces.Repositories;
global using Authentication.Application.Interfaces.Services;
global using Authentication.Application.Models.MasterData;
global using Authentication.Application.Models.Users.Contexts;
global using Authentication.Domain.Entities;
global using Authentication.Domain.Enums;
global using Authentication.Infrastructure.Constants;
global using Authentication.Infrastructure.Context;
global using Authentication.Infrastructure.Dependencies;
global using Authentication.Infrastructure.Helpers;
global using Authentication.Infrastructure.Models.Authentications.Sessions;
global using Authentication.Infrastructure.Models.MasterData;
global using Authentication.Infrastructure.Models.Users.Kyc;
global using Authentication.Infrastructure.Models.Users.Profiles;
global using Authentication.Infrastructure.Options.Authentications;
global using Authentication.Infrastructure.Options.ExternalProviders;
global using Authentication.Infrastructure.Repositories;
global using Authentication.Infrastructure.Services;
global using Be.Haven.Core.Exceptions;
global using Be.Haven.Core.Extensions.DI;
global using Be.Haven.Core.Extensions.Objects;
global using Be.Haven.Core.Helpers;
global using Be.Haven.Core.Interfaces.Caches;
global using Be.Haven.Core.Interfaces.Repositories;
global using Be.Haven.Core.Interfaces.Services;
global using Be.Haven.Core.Models.ClientDevices;
global using Be.Haven.Core.Models.ObjectStorage;
global using Be.Haven.Core.Repositories;
global using Be.Haven.Core.Services;
global using Be.Haven.Shared.Constants.System;
global using Be.Haven.Shared.Dtos;
global using Be.Haven.Shared.Dtos.Options.Email;
global using Be.Haven.Shared.Dtos.Options.Storage;
global using Be.Haven.Shared.Dtos.Requests.Emails;
global using Mapster;
global using Microsoft.AspNetCore.Http;
global using Microsoft.AspNetCore.Identity;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.Metadata.Builders;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Logging;
global using Microsoft.Extensions.Options;
global using Microsoft.IdentityModel.Protocols;
global using Microsoft.IdentityModel.Protocols.OpenIdConnect;
global using Microsoft.IdentityModel.Tokens;
global using Npgsql;
global using static Authentication.Domain.Constants.AuthenticationMasterDataCodes;
global using static Authentication.Infrastructure.Constants.InfrastructureConstants;
global using static Authentication.Infrastructure.Constants.PostgreSqlConfigurationConstants;
global using static Be.Haven.Shared.Constants.System.AppConstants.SystemMessageCode;
global using static Be.Haven.Shared.Constants.Authentication.AuthConstants;
global using static Be.Haven.Shared.Constants.Authentication.AuthConstants.SystemMessage;
global using static Be.Haven.Shared.Constants.Storage.ObjectStorageConstants;
