// Global using directives

global using System.IdentityModel.Tokens.Jwt;
global using System.Security.Claims;
global using System.Security.Cryptography;
global using System.Text;
global using Authentication.Application.Commands.ChangeForgotPassword;
global using Authentication.Application.Commands.ChangePassword;
global using Authentication.Application.Commands.ExternalLink;
global using Authentication.Application.Commands.ForgotPassword;
global using Authentication.Application.Commands.Register;
global using Authentication.Application.Commands.ThirdPartyLogin;
global using Authentication.Application.Commands.VerifyForgotPasswordOtp;
global using Authentication.Application.Commands.VerifyRegisterEmail;
global using Authentication.Application.Dtos.Authentications;
global using Authentication.Application.Dtos.Users;
global using Authentication.Application.Interfaces;
global using Authentication.Application.Interfaces.Repositories;
global using Authentication.Application.Options;
global using Authentication.Domain.Entities;
global using Authentication.Infrastructure.Constants;
global using Authentication.Infrastructure.Context;
global using Authentication.Infrastructure.Options;
global using Authentication.Infrastructure.Repositories;
global using Authentication.Infrastructure.Services;
global using Be.Haven.Core.Extensions.DI;
global using Be.Haven.Core.Interfaces.Caches;
global using Be.Haven.Core.Interfaces.Repositories;
global using Be.Haven.Core.Interfaces.Services;
global using Be.Haven.Core.Repositories;
global using Be.Haven.Core.Services;
global using Be.Haven.Shared.Dtos;
global using Be.Haven.Shared.Dtos.Requests.Emails;
global using Microsoft.AspNetCore.Identity;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.Metadata.Builders;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Logging;
global using Microsoft.Extensions.Options;
global using Microsoft.IdentityModel.Protocols;
global using Microsoft.IdentityModel.Protocols.OpenIdConnect;
global using Microsoft.IdentityModel.Tokens;
global using static Authentication.Infrastructure.Constants.InfrastructureConstants;
global using static Authentication.Infrastructure.Constants.InfrastructureErrorConstants;
global using static Authentication.Infrastructure.Constants.InfrastructureLogConstants;
global using static Authentication.Application.Constants.ApplicationErrorConstants;
