namespace Be.Haven.Shared.Dtos.Responses;

/// <summary>
/// Represents the response returned after uploading a file to GCP.
/// </summary>
public class UploadGcpResponse
{
    /// <summary>
    /// Gets or sets the unique identifier representing the uploaded file.
    /// This value typically corresponds to an object ID or resource ID generated by GCP.
    /// </summary>
    public Guid Data { get; set; }

    /// <summary>
    /// Indicates whether the upload operation was successful.
    /// </summary>
    public bool Success { get; set; }

    /// <summary>
    /// Contains the error message when the upload fails.
    /// If <see cref="Success"/> is true, this value is usually null or empty.
    /// </summary>
    public string Error { get; set; }
}
