// Global using directives
global using System.Data;
global using System.Net.Http.Headers;
global using System.Text.Json.Serialization;
global using System.Text.RegularExpressions;
global using Be.Haven.Shared.Configurations;
global using Be.Haven.Shared.Constants;
global using Be.Haven.Shared.Dtos.Options.Authentications;
global using Be.Haven.Shared.Dtos.Options.Caching;
global using Be.Haven.Shared.Dtos.Options.Data;
global using Be.Haven.Shared.Dtos.Options.Email;
global using Be.Haven.Shared.Dtos.Options.Gcp;
global using Be.Haven.Shared.Dtos.Options.Observability;
global using Be.Haven.Shared.Dtos.Options.Scheduling;
global using Be.Haven.Shared.Dtos.Options.Storage;
global using Be.Haven.Shared.Enums;
global using Dapper;
global using Microsoft.AspNetCore.Http;
global using Newtonsoft.Json;
global using Serilog.Events;
global using static Be.Haven.Shared.Constants.AppConstants.SystemVariable;
global using static Be.Haven.Shared.Constants.ObjectStorageConstants;
global using JsonIgnore = System.Text.Json.Serialization.JsonIgnoreAttribute;
