<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>disable</Nullable>
        <LangVersion>14</LangVersion>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <NoWarn>$(NoWarn);1591</NoWarn>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Be.Haven.Core\Be.Haven.Core.csproj" />
      <ProjectReference Include="..\Be.Haven.Shared\Be.Haven.Shared.csproj" />
    </ItemGroup>

    <ItemGroup>
      <EmbeddedResource Include="Swagger\Assets\*.js" />
    </ItemGroup>

</Project>
