// Global using directives

global using System.Diagnostics;
global using System.IdentityModel.Tokens.Jwt;
global using System.Net;
global using System.Net.Http.Headers;
global using System.Reflection;
global using System.Security.Claims;
global using System.Text.Encodings.Web;
global using System.Text.Json;
global using System.Text.RegularExpressions;
global using Asp.Versioning;
global using Asp.Versioning.ApiExplorer;
global using Be.Haven.ApiCommon.Filters;
global using Be.Haven.ApiCommon.Middlewares;
global using Be.Haven.ApiCommon.Options;
global using Be.Haven.Core.Exceptions;
global using Be.Haven.Core.Extensions.Objects;
global using Be.Haven.Core.Formatters;
global using Be.Haven.Core.Helpers;
global using Be.Haven.Shared.Constants;
global using Be.Haven.Shared.Dtos;
global using Be.Haven.Shared.Dtos.Options;
global using Microsoft.AspNetCore.Authentication;
global using Microsoft.AspNetCore.Builder;
global using Microsoft.AspNetCore.Diagnostics.HealthChecks;
global using Microsoft.AspNetCore.Http;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.AspNetCore.Mvc.Filters;
global using Microsoft.AspNetCore.Mvc.Infrastructure;
global using Microsoft.AspNetCore.Mvc.ModelBinding;
global using Microsoft.AspNetCore.Routing;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Diagnostics.HealthChecks;
global using Microsoft.Extensions.Logging;
global using Microsoft.Extensions.Options;
global using Microsoft.IdentityModel.Protocols;
global using Microsoft.IdentityModel.Protocols.OpenIdConnect;
global using Microsoft.IdentityModel.Tokens;
global using Microsoft.OpenApi;
global using Newtonsoft.Json;
global using Newtonsoft.Json.Serialization;
global using OpenTelemetry.Resources;
global using Serilog;
global using Serilog.Context;
global using Serilog.Enrichers.OpenTelemetry;
global using Serilog.Events;
global using Serilog.Extensions.Hosting;
global using Swashbuckle.AspNetCore.SwaggerGen;
global using Swashbuckle.AspNetCore.SwaggerUI;
global using static Be.Haven.Shared.Constants.AppConstants.MethodCode;
global using static Be.Haven.Shared.Constants.AppConstants.ODataConstant;
global using static Be.Haven.Shared.Constants.AppConstants.SystemMessage;
global using static Be.Haven.Shared.Constants.AppConstants.SystemMessageCode;
global using static Be.Haven.Shared.Constants.AppConstants.SystemVariable;
global using static Be.Haven.Shared.Constants.CoreLogConstants;
global using static Be.Haven.Shared.Constants.AuthConstants.SystemMessage;
global using static Be.Haven.Shared.Constants.AuthConstants;
global using static Be.Haven.Shared.Constants.ApiLogConstants;
global using static Be.Haven.Shared.Constants.ApiConstants;
global using static Be.Haven.Shared.Constants.ApiConstants.SwaggerConstants;
global using static Be.Haven.Shared.Constants.AppConstants;
global using static Be.Haven.Shared.Constants.ValidationMessage;