namespace Haven.ApiCommon.Extensions;

public static class ServiceRegistration
{
    /// <summary>
    /// Configures Swagger/OpenAPI services for the application.
    /// This includes adding versioning support, sorting endpoints alphabetically, grouping by versions,
    /// and enabling annotations to enhance API documentation.
    /// </summary>
    /// <param name="services">The service collection to which Swagger services are added.</param>
    public static void AddConfiguredSwagger(this IServiceCollection services)
    {
        services.AddSwaggerGen(options =>
        {
            // Configure JWT Bearer authentication for Swagger UI
            options.AddSecurityDefinition(BEARER, new OpenApiSecurityScheme
            {
                Type = SecuritySchemeType.Http,
                Scheme = BEARER,
                BearerFormat = JWT,
                In = ParameterLocation.Header,
                Name = AUTHORIZATION,
                Description = AUTH_DESCRIPTION
            });

            // Apply Bearer auth globally
            options.AddSecurityRequirement(new OpenApiSecurityRequirement
            {
                {
                    new OpenApiSecurityScheme
                    {
                        Reference = new OpenApiReference
                        {
                            Type = ReferenceType.SecurityScheme,
                            Id = BEARER
                        }
                    },
                    Array.Empty<string>()
                }
            });

            // Keep Swagger UI clean and consistent
            options.OrderActionsBy(apiDesc => $"{apiDesc.HttpMethod} {apiDesc.RelativePath}");
            
            // Read XML comments generated by the current API assembly
            var xmlFile = string.Format(XML_DOC_FILE_FORMAT, Assembly.GetExecutingAssembly().GetName().Name);
            var xmlPath = Path.Combine(AppContext.BaseDirectory, xmlFile);

            if (File.Exists(xmlPath))
            {
                options.IncludeXmlComments(xmlPath, includeControllerXmlComments: true);
            }
            
            // Enables Swagger annotations to enrich endpoint metadata in Swagger UI.
            options.EnableAnnotations();

            // Include only endpoints of the current API version
            options.DocInclusionPredicate((docName, apiDesc) =>
                apiDesc.GroupName == null || apiDesc.GroupName == docName);
            
            // Ensure consistent path parameter naming in Swagger.
            options.OperationFilter<KebabCaseSwaggerFilter>();
        });

        // Auto-generate Swagger docs for all API versions (v1, v2, ...)
        services.AddTransient<IConfigureOptions<SwaggerGenOptions>, ConfigureSwaggerOptions>();
    }
}