namespace Haven.Application.Commands.ConfirmTenantJoin;

/// <summary>
/// Validates tenant QR join confirmation.
/// </summary>
public class ConfirmTenantJoinCommandValidator : AbstractValidator<ConfirmTenantJoinCommand>
{
    /// <summary>
    /// Creates validation rules for QR join confirmation.
    /// </summary>
    public ConfirmTenantJoinCommandValidator()
    {
        // Confirm must use the short-lived token generated by the backend QR endpoint.
        RuleFor(x => x.Token).Required().MaxLen(TENANT_JOIN_TOKEN_MAX_LENGTH);
    }
}
