namespace Haven.Application.Constants;

/// <summary>
/// Stores Haven property module constants shared by commands, queries, and services.
/// </summary>
public static class ApplicationConstants
{
    /// <summary>
    /// Default page number for property listing.
    /// </summary>
    public const int DEFAULT_PAGE_NUMBER = 1;

    /// <summary>
    /// Default page size for property listing.
    /// </summary>
    public const int DEFAULT_PROPERTY_PAGE_SIZE = 20;

    /// <summary>
    /// Maximum page size accepted by property listing.
    /// </summary>
    public const int MAX_PROPERTY_PAGE_SIZE = 100;

    /// <summary>
    /// Maximum number of floors generated by the quick structure setup.
    /// </summary>
    public const int MAX_GENERATED_FLOORS = 200;

    /// <summary>
    /// Maximum number of rooms generated per floor by the quick structure setup.
    /// </summary>
    public const int MAX_GENERATED_ROOMS_PER_FLOOR = 100;

    /// <summary>
    /// Maximum total units generated in a single property create request.
    /// </summary>
    public const int MAX_GENERATED_UNITS = 1000;

    /// <summary>
    /// Master-data type code for party types.
    /// </summary>
    public const string MASTER_TYPE_PARTY_TYPE = "PartyType";

    /// <summary>
    /// Master-data type code for party statuses.
    /// </summary>
    public const string MASTER_TYPE_PARTY_STATUS = "PartyStatus";

    /// <summary>
    /// Master-data type code for property types.
    /// </summary>
    public const string MASTER_TYPE_PROPERTY_TYPE = "PropertyType";

    /// <summary>
    /// Master-data type code for property statuses.
    /// </summary>
    public const string MASTER_TYPE_PROPERTY_STATUS = "PropertyStatus";

    /// <summary>
    /// Master-data type code for unit types.
    /// </summary>
    public const string MASTER_TYPE_UNIT_TYPE = "UnitType";

    /// <summary>
    /// Master-data type code for unit rental modes.
    /// </summary>
    public const string MASTER_TYPE_UNIT_RENTAL_MODE = "UnitRentalMode";

    /// <summary>
    /// Master-data type code for unit statuses.
    /// </summary>
    public const string MASTER_TYPE_UNIT_STATUS = "UnitStatus";

    /// <summary>
    /// Master-data type code for unit package type values.
    /// </summary>
    public const string MASTER_TYPE_UNIT_PACKAGE_TYPE = "UnitPackageType";

    /// <summary>
    /// Master-data type code for unit package status values.
    /// </summary>
    public const string MASTER_TYPE_UNIT_PACKAGE_STATUS = "UnitPackageStatus";

    /// <summary>
    /// Master-data type code for gender restrictions.
    /// </summary>
    public const string MASTER_TYPE_GENDER_RESTRICTION = "GenderRestriction";

    /// <summary>
    /// Master-data type code for property-party relationship types.
    /// </summary>
    public const string MASTER_TYPE_PROPERTY_RELATIONSHIP_TYPE = "PropertyRelationshipType";

    /// <summary>
    /// Master-data type code for invoice line types.
    /// </summary>
    public const string MASTER_TYPE_INVOICE_LINE_TYPE = "InvoiceLineType";

    /// <summary>
    /// Master-data type code for vehicle types.
    /// </summary>
    public const string MASTER_TYPE_VEHICLE_TYPE = "VehicleType";

    /// <summary>
    /// Master-data type code for common active/inactive values.
    /// </summary>
    public const string MASTER_TYPE_COMMON_STATUS = "CommonStatus";

    /// <summary>
    /// Landlord party type code.
    /// </summary>
    public const string MASTER_CODE_PARTY_TYPE_LANDLORD = "LANDLORD";

    /// <summary>
    /// Active party/common status code.
    /// </summary>
    public const string MASTER_CODE_ACTIVE = "ACTIVE";

    /// <summary>
    /// Draft property status used for newly created properties.
    /// </summary>
    public const string MASTER_CODE_PROPERTY_STATUS_DRAFT = "DRAFT";

    /// <summary>
    /// Available unit status used for generated rooms.
    /// </summary>
    public const string MASTER_CODE_UNIT_STATUS_AVAILABLE = "AVAILABLE";

    /// <summary>
    /// Default package type used when a generated unit has no selected service/furniture package.
    /// </summary>
    public const string MASTER_CODE_UNIT_PACKAGE_TYPE_NO_FURNITURE = "NO_FURNITURE";

    /// <summary>
    /// Custom package type used for service/furniture packages defined during property setup.
    /// </summary>
    public const string MASTER_CODE_UNIT_PACKAGE_TYPE_CUSTOM = "CUSTOM";

    /// <summary>
    /// Active package status used for generated default unit packages.
    /// </summary>
    public const string MASTER_CODE_UNIT_PACKAGE_STATUS_ACTIVE = "ACTIVE";

    /// <summary>
    /// Invoice line type code used for parking charge policies.
    /// </summary>
    public const string MASTER_CODE_INVOICE_LINE_TYPE_PARKING = "PARKING";

    /// <summary>
    /// Default unit type when the request does not provide one.
    /// </summary>
    public const string MASTER_CODE_UNIT_TYPE_ROOM = "ROOM";

    /// <summary>
    /// Unit type code used for a unit that represents one rentable floor.
    /// </summary>
    public const string MASTER_CODE_UNIT_TYPE_FLOOR = "FLOOR";

    /// <summary>
    /// Default rental mode when the request does not provide one.
    /// </summary>
    public const string MASTER_CODE_RENTAL_MODE_WHOLE_UNIT = "WHOLE_UNIT";

    /// <summary>
    /// Rental mode code used when several primary tenants rent beds in one room.
    /// </summary>
    public const string MASTER_CODE_RENTAL_MODE_SHARED_BED = "SHARED_BED";

    /// <summary>
    /// Property relationship codes allowed to access landlord-facing property reads.
    /// </summary>
    public static readonly IReadOnlyCollection<string> PROPERTY_ACCESS_RELATIONSHIP_CODES =
        Enum.GetValues<PropertyRelationshipTypeEnum>()
            .Select(x => x.ToMasterDataCode())
            .ToArray();

    /// <summary>
    /// Calculation-method code that maps to usage-based charge policies.
    /// </summary>
    public const string CALCULATION_METHOD_METER_READING = "METER_READING";

    /// <summary>
    /// Calculation-method code that maps to fixed charge policies.
    /// </summary>
    public const string CALCULATION_METHOD_FIXED = "FIXED";

    /// <summary>
    /// Prefix used for auto-generated property codes.
    /// </summary>
    public const string PROPERTY_CODE_PREFIX = "PROP";

    /// <summary>
    /// Number of random characters kept in generated property codes.
    /// </summary>
    public const int PROPERTY_CODE_RANDOM_LENGTH = 10;

    /// <summary>
    /// Maximum attempts for generating an unused property code.
    /// </summary>
    public const int PROPERTY_CODE_MAX_ATTEMPTS = 5;

    /// <summary>
    /// Prefix used for package options generated during quick property setup.
    /// </summary>
    public const string UNIT_PACKAGE_CODE_PREFIX = "PKG";

    /// <summary>
    /// Location kind label used when resolving province codes.
    /// </summary>
    public const string LOCATION_KIND_PROVINCE = "province";

    /// <summary>
    /// Location kind label used when resolving district codes.
    /// </summary>
    public const string LOCATION_KIND_DISTRICT = "district";

    /// <summary>
    /// Location kind label used when resolving ward codes.
    /// </summary>
    public const string LOCATION_KIND_WARD = "ward";

    /// <summary>
    /// Default quick setup room numbering pattern.
    /// </summary>
    public const string DEFAULT_ROOM_NUMBERING_PATTERN = "{floor}{room}";

    /// <summary>
    /// Error message used when the authenticated user cannot be resolved.
    /// </summary>
    public const string ERROR_AUTHENTICATED_USER_REQUIRED = "Authenticated user is required.";

    /// <summary>
    /// Error message used when the current party context is missing.
    /// </summary>
    public const string ERROR_CURRENT_PARTY_REQUIRED = "Current party context is required.";

    /// <summary>
    /// Error message used when create property is attempted outside landlord context.
    /// </summary>
    public const string ERROR_LANDLORD_CONTEXT_REQUIRED = "Current party must be an active landlord context to manage properties.";

    /// <summary>
    /// Error message used when a property cannot be found in the current party scope.
    /// </summary>
    public const string ERROR_PROPERTY_NOT_FOUND = "Property was not found in the current party scope.";

    /// <summary>
    /// Error message template used when a master-data value cannot be resolved.
    /// </summary>
    public const string ERROR_MASTER_DATA_NOT_FOUND = "Master-data value '{0}:{1}' was not found or inactive.";

    /// <summary>
    /// Error message template used when a location code cannot be resolved.
    /// </summary>
    public const string ERROR_LOCATION_NOT_FOUND = "Location code '{0}:{1}' was not found.";

    /// <summary>
    /// Error message used when property-code generation cannot find a free code.
    /// </summary>
    public const string ERROR_PROPERTY_CODE_GENERATION_FAILED = "Could not generate a unique property code.";

    /// <summary>
    /// Log template for property list query completion at the application boundary.
    /// </summary>
    public const string LOG_PROPERTY_LIST_QUERY_COMPLETED = "Property list query completed for party {PartyPublicId}.";

    /// <summary>
    /// Log template for property detail query completion at the application boundary.
    /// </summary>
    public const string LOG_PROPERTY_DETAIL_QUERY_COMPLETED =
        "Property detail query completed for property {PropertyPublicId} and party {PartyPublicId}.";

    /// <summary>
    /// Log template for property creation command completion at the application boundary.
    /// </summary>
    public const string LOG_PROPERTY_CREATE_COMMAND_COMPLETED =
        "Property create command completed for property {PropertyPublicId} and party {PartyPublicId}.";

}
