// Global using directives
global using System.Text.Json.Serialization;
global using Asp.Versioning;
global using Be.Haven.ApiCommon.Extensions;
global using Be.Haven.ApiCommon.Factories;
global using Be.Haven.ApiCommon.Filters;
global using Be.Haven.ApiCommon.Middlewares;
global using Be.Haven.ApiCommon.Routing;
global using Be.Haven.Cache.Extensions;
global using Be.Haven.Core.Extensions.Configurations;
global using Be.Haven.Core.Extensions.DI;
global using Be.Haven.Core.Factories;
global using Be.Haven.Shared.Dtos.Options.Authentications;
global using Be.Haven.Shared.Dtos.Options.Gcp;
global using Be.Haven.Shared.Dtos;
global using Be.Haven.Shared.Dtos.Responses;
global using Haven.Api.Constants;
global using Haven.Api.Extensions;
global using Haven.Application.Extensions;
global using Haven.Application.Commands.CreateProperty;
global using Haven.Application.Dtos.Properties.Common;
global using Haven.Application.Dtos.Properties.Create;
global using Haven.Application.Dtos.Properties.Detail;
global using Haven.Application.Dtos.Properties.List;
global using Haven.Application.Queries.GetProperties;
global using Haven.Application.Queries.GetPropertyDetail;
global using Mediator;
global using Microsoft.AspNetCore.Authorization;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.AspNetCore.Mvc.ApplicationModels;
global using Microsoft.AspNetCore.Server.Kestrel.Core;
global using Microsoft.Extensions.Hosting;
global using static Be.Haven.Shared.Constants.AppConstants.SystemVariable;
global using static Be.Haven.Shared.Constants.AuthConstants;
global using static Be.Haven.Shared.Constants.CoreLogConstants;
global using static Be.Haven.Shared.Constants.ApiConstants;
global using static Be.Haven.Shared.Constants.AuthConstants.SystemMessage;
global using static Haven.Api.Constants.ControllerRouteConstants;

